# If enabled, died players can't move in spectator mode so they can't find any secret thing or watch something
freeze-dead: true

# If enabled, a particle appears when reviving players
revive-particles: true

# If enabled, died but offline players can be revived
offline-revives: false

# Announcment options
announce:

  # If enabled, reviving a player makes announcment
  revived: false

  # If enabled, crafting a player head makes announcment
  crafted: false

  # If enabled, killing a player makes announcment still if announceDeathMessages is closed on server
  slain: false


# All message customazition
# note: TC means that message is sends to console
messages:

  # Sends when a player is revived
  revived-announcement: '%reviver% &rrevived %revived%'

  # Sends when a player crafted a player head
  crafted-announcement: '%player% &rcrafted a revive head'

  # Sends when a player kills someone
  slain-announcement: '%killer% &rkilled %victim%'

  # Sends to console when plugin is in the last version
  up-to-date: 'Plugin is up to date'

  #TC - Sends when a plugin update is avaliable
  update-available-console: 'Plugin has an update. Please download it from here: https://www.spigotmc.org/resources/awakensmp-online.102573/'

  # Sends when a plugin update is avaliable to operators
  update-available-player: '&a[AwakenSMPOnline] &6Plugin has an update. Please download it from here: https://www.spigotmc.org/resources/awakensmp-online.102573/'

  # Sends when player don't have required permisison
  no-perm: '&cYou don''t have permission to do that!'

  # Appears on the offline player holograms
  offline-hologram: '&e%player% will respawn here'

  # Sends to players that revived when ther are offline
  revive-notification: 'Someone revived you here when you''re offline!'

  # Sends when a player head is placed:

  #  But player is not dead
  not-dead: '&cThis player is not dead'

  #  But head name is invalid
  invalid-name: '&cCouldn''t found a player named that'

  #  But player is offline and can't be revived
  not-online: '&cThis player is dead but not online'

  # Sends when command is only avaliable for players
  not-player: '&cOnly players can use this command.'

  # Command message options
  commands:

    # Sends when /awakensmp reloadconfig is used
    reloadconfig: '&aReloaded Config!'

    # Sends all when /awakensmp deadplayers is use
    deadplayers:

      # Header of the list
      header: '&4-----&cDead Players&4-----'

      # Player syntax of the list
      format: '- %player%'

      # If no one is dead, this appears
      none: 'No one was dead yet.'

    # Main help command
    main:

      # Header
      header: '&2----------&aHelp Menu&2----------'

      # Command format of the list
      command-format: '&e%syntax% &6- &f%description%'

      # description of /awakensmp deadplayers
      desc-dp: 'See how many players are dead'

      # description of /awakensmp reloadconfig
      desc-rc: 'Reloads the config'

      # description of /awakensmp revive
      desc-rvv: 'Revive a player without a head'

      # description of /awakensmp settings
      desc-opt: 'Change some options in-game'

      # description of /smp particle
      desc-prt: 'Customize your own revive particle'

      # Footer
      footer: '&2-----------------------------'

    # /awakensmp revive command
    revive:

      # Sends when player not gived a player name
      no-arg: '&cMust give a player name to revive him. Usage: /awakensmp revive <player>'

      # Sends when player gived a wrong player name
      wrong-arg: '&cMust give a VALID player name to revive him. Usage: /awakensmp revive <player>'

      # Sends when player gived a player name but player is not dead
      not-dead: '&cMust give a DEAD player name to revive him. Usage: /awakensmp revive <player>'

      # Sends when the player is successfully revived
      success: '&aRevived player!'

      # Sends when /awakensmp revive all is used
      all:

        # Sends when no one is dead
        no-dead: '&cNo one is dead'

        # Sends as warning when some dead players are offline and can't be revived
        offline-players: '&6%count% Player(s) are offline so they can''t be revived now because offline revives is closed on server'

        # Sends when all players are offline and can't be revived
        all-offline: '&cAll players that dead is offline'

        # Sends when all or all online players are succesfully revived
        success: '&aRevived players!'

    # /awakensmp settings command
    settings:

      # Header
      header: '&4----------&cSettings&4----------'

      # freeze-dead option
      freeze-dead: '&fFreeze Dead Players'

      # revive-particles option
      revive-particles: '&fParticles &7(when revived)'

      # offline-revives option
      offline-revives:  '&fOffline Player Reviving'

      # announce.slain option
      announce-slain: '&fAnnounce When Player Killed'

      # announce.craft option
      announce-craft: '&fAnnounce When Revive Head Crafted'

      # announce.revive option
      announce-revive: '&fAnnounce When Player Revived'

      # recipe.use-default option
      use-default: '&fUse Default Recipe:'

      # recipe.name option
      head-name: '&fRevive Head Name'

      # recipe.desc option
      head-desc: '&fRevive Head Description'

      # Footer
      footer: '&4---------------------------'

      # Enabled text for toggle options
      boolean-true: '&a&l[ENABLED]'

      # Disabled text for toggle options
      boolean-false: '&c&l[DISABLED]'

      # Disabled text's hover for toggle options
      boolean-enable: '&eClick to enable it'

      # Enabled text's hover for toggle options
      boolean-disable: '&eClick to disable it'

      # Edit text for text options
      string: '&e&l[EDIT]'

      # Suffix after option name for text options
      string-option-suffix: '&f:&d'

      # Edit text's hover for text options
      string-desc: '&eClick to edit it'

      # Message option in command for text options
      string-desc-cmd: '<message here, &sp to use space>'

    # /smp particle command
    particle-menu:

      # Main menu title
      main-title: 'Particle Options'

      # Type menu title
      type-title: 'Select a Particle Type'

      # Color menu title
      color-title: 'Select a Particle Color'

      # Close button
      btn-close: '&cClose'

      # Back button
      btn-back: '&eBack'

      # Change Color button in main menu
      main-color: '&f&lChange Color'

      # Change Style button in main menu
      main-style: '&f&lChange Style'

      # White color
      color-white: '&#eaeded&lWhite'

      # Orange color
      color-orange: '&#f17716&lOrange'

      # Magenta color
      color-magenta: '&#be46b5&lMagenta'

      # Light Blue color
      color-light-blue: '&#3cb0da&lLight Blue'

      # Yellow color
      color-yellow: '&#f9c629&lYellow'

      # Lime color
      color-lime: '&#71ba1a&lLime'

      # Pink color
      color-pink: '&#ee90ad&lPink'

      # Gray color
      color-gray: '&#3f4548&lGray'

      # Light Gray color
      color-light-gray: '&#8e8f87&lLight Gray'

      # Cyan color
      color-cyan: '&#158a91&lCyan'

      # Purple color
      color-purple: '&#7b2bad&lPurple'

      # Blue color
      color-blue: '&#353a9e&lBlue'

      # Brown color
      color-brown: '&#734829&lBrown'

      # Green color
      color-green: '&#556e1c&lGreen'

      # Red color
      color-red: '&#a12823&lRed'

      # Black color
      color-black: '&#2e2e37&lBlack'

      # Explosion type
      type-explosion: '&f&lExplosion'

      # Pop type
      type-pop: '&f&lPop'

      # Puff type
      type-puff: '&f&lPuff'

      # Dust type
      type-dust: '&f&lDust'

      # Bean type
      type-beam: '&f&lBeam'

      # Potion type
      type-potion: '&f&lPotion'

      # Totem type
      type-totem: '&f&lTotem'

  # Some main command arguments
  command-args:

    # Required player
    player: '<player>'

    # Optional option name (for /awakensmp settings)
    sett-option: '[option]'

    # Optional option value (for /awakensmp settings)
    sett-value: '[value]'


# Custom head recipe options
recipe:

  # If enabled, all of this will be ignored and server uses default recipe in spigot page
  use-default: true

  # Recipe shape. Must be 3 lines and 3 letter for each line. Each letter means a key for a material.
  shape:
    - 'DND'
    - 'TWT'
    - 'DND'

  # Material keys. for all material names can be writable to a key, see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  materials:
    D: 'DIAMOND_BLOCK'
    T: 'TOTEM_OF_UNDYING'
    W: 'NETHER_STAR'
    N: 'NETHERITE_INGOT'
    a: 'AIR'

  # Item player head options
  head:

    # Item's name
    name: '&eRevive Head'

    # Item's lore
    desc: '&eRename it to revive a player!'

# Recommended to not change this
version: "1.5.1"