name: AwakenSMPOnline
version: '${project.version}'
main: me.efekos.awakensmponline.AwakenSMPOnline
api-version: 1.19
authors: [ efekos ]
description: AwakenSMP System with advanced features
website: https://www.spigotmc.org/resources/awakensmp-online.102573/
