name: AwakenSMPOnline
version: '${project.version}'
main: me.efekos.awakensmponline.AwakenSMPOnline
api-version: 1.18
authors: [ efekos ]
description: A SMP plugin like AwakenSMP
website: https://www.spigotmc.org/resources/awakensmp-online.102573/